server.port=8083

spring.application.name=yard-service

spring.datasource.url=jdbc:postgresql://localhost:5432/yard-service-port
spring.datasource.username=postgres
spring.datasource.password=212007
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true