server.port=8081

spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/authservice-port
spring.datasource.username=postgres
spring.datasource.password=212007
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost